### ISSUE TITLE
Shortcode Placeholder Regex

### ISSUE THREAD

**Issue by rodleviton** [swanky-docs/swanky-webpack-plugin#25]
@uglow The regex here https://github.com/swanky-docs/swanky-webpack-plugin/blob/master/src/utils/shortcode.js#L58 seems to match `sWaNkY-md-1` against a placeholder starting with the index e.g. `sWaNkY-md-10` & `sWaNkY-md-11`. We need to update regex to match complete placeholder e.g. not one with trailing digits.

**Comment by uglow** [comment]
@rodleviton I think the fix is simple: append another "closing" character to the end of the token. e.g.: sWaNkY-md-10! I'm pressed for time at the moment. Do you think you could implement this?
